### ISSUE TITLE
Integration test searches temp DB conf file from wrong location

### ISSUE THREAD

**Issue by msokk** [didit-tech/FastLegS#1]
/test/integration/../../.fastlegs should be
test/integration/../bootstrap/.fastlegs

**Comment by malkomalko** [comment]
hi msokk, it looks like the .fastlegs file on my end gets created in the root directory of the project and not in the boostrap folder when I run it.  In that case the directory tree looks correct.

Are you running make test from the root of the project?

**Comment by msokk** [comment]
Hi, I ran it from project root with  "make test"

Error message is as follows : integration_test.js integrates: Error: EBADF, Bad file descriptor '/home/dev/TapTender/FastLegS/test/integration/../../.fastlegs'

Actually there is no .fastlegs anywhere in the project after running tests

I'm using:
Node version: 0.4.2
Ubuntu 10.10

OT: What's with the name? :)

**Comment by malkomalko** [comment]
I think I know what the problem is and I'll look into fixing it.  When you run make test it should ask you to fill in your database settings.  If for whatever reason you type in wrong connection information or if you choose a database that already exists it will fail silently because it's trying to create a database for you.

DOH!

Can you try running make test again putting in valid credentials and a new database name just for testing purposes and try again?

I'll make the creation a little more robust.

As for the name, we built this to work with some legacy database tables and will have features in the near future to allow for column mappings.  The idea was to get up and running quickly with any type of database you want to throw at it.

**Comment by msokk** [comment]
Yup, it worked with new db, same problem happens with wrong password too, just a matter of giving more feedback on credential input. 

Ah yes, up and running, fast, but the camelcase?

**Comment by malkomalko** [comment]
Fast Legacy Service :P
